### ISSUE TITLE
error in figure_4.py

### ISSUE THREAD

**Issue by bthirion** [alexblnn/Notip#4]
TypeError                                 Traceback (most recent call last)
~/mygit/alexandre_blain/posthoc-fmri/scripts/figure_4.py in <module>
     46 # Compute largest region sizes for 3 possible TDP values
     47 
---> 48 res_01 = compute_bounds(test_task1s, test_task2s, learned_templates, alpha,
     49                         0.95, k_max, B, smoothing_fwhm=smoothing_fwhm,
     50                         seed=seed)

~/mygit/alexandre_blain/posthoc-fmri/scripts/posthoc_fmri.py in compute_bounds(task1s, task2s, learned_templates, alpha, TDP, k_max, B, smoothing_fwhm, seed)
    406                                                       nifti_masker)
    407 
--> 408         _, region_size_learned = sa.find_largest_region(p_values,
    409                                                         calibrated_tpl,
    410                                                         TDP,

~/mygit/sanssouci.python/sanssouci/post_hoc_bounds.py in find_largest_region(p_values, thresholds, tdp, masker)
    273     z_map_ = norm.isf(p_values)
    274 
--> 275     res = curve_min_tdp(p_values, thresholds)
    276     region_size = len(res[res > tdp])
    277     pval_cutoff = sorted(p_values)[region_size - 1]

~/mygit/sanssouci.python/sanssouci/post_hoc_bounds.py in curve_min_tdp(p_values, thresholds)
    244     p = p_values.shape[0]
    245     range = np.arange(1, p + 1)  # use this to shorten following line
--> 246     return (range - curve_max_fp(p_values, thresholds)) / range
    247 
    248 

~/mygit/sanssouci.python/sanssouci/post_hoc_bounds.py in curve_max_fp(p_values, thresholds)
    162         print("The input p-values were not sorted -> this is done now")
    163 
--> 164     if np.linalg.norm(thresholds - thresholds[np.argsort(thresholds)]) \
    165        > 0.0001:
    166         thresholds = thresholds[np.argsort(thresholds)]

TypeError: 'int' object is not subscriptable

In [3]: %debug

**Comment by alexblnn** [comment]
fixed some time ago, closing.
